name: Build Prescreening Docker Image

on:
  workflow_dispatch:
  push:
    branches:
      - "dev"
  pull_request:
    branches:
      - "dev"
env:
  TEST_TAG: ${{ secrets.DOCKERHUB_USERNAME }}/clientservice:test
  LATEST_TAG: ${{ secrets.DOCKERHUB_USERNAME }}/clientservice:latest
  DU: ${{ secrets.DOCKERHUB_USERNAME }}
  DT: ${{ secrets.DOCKERHUB_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ env.DU }}
          password: ${{ env.DT }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and export to Docker
        uses: docker/build-push-action@v4
        with:
          build-args: |
            gituser=${{ secrets.USERNAME }}
            gitpass=${{ secrets.PAT }}
            dbpass=password
            dbuser=user
            dbport=1111
            dbname=db
            dbhost=localhost
            mquser=user
            mqpass=mqpassword
            mqhost=localhost
            mqport=2222
          context: .
          load: true
          file: ./src/Presentation/ClientServiceApi/Dockerfile
          tags: ${{ env.TEST_TAG }}

      - name: Test container
        run: |
          CID=$(docker run -d --rm -p '8080:80' ${{ env.TEST_TAG }})
          if [[ -n "$CID" ]]; then
            sleep 5
            docker exec "$CID" /bin/bash -c "/bin/echo 'this is within the container'" && \
            docker stop "$CID"
            exit 0
          else
            echo "Unable to run container with test image" 1>&2
            exit 1
          fi

      - name: Push container
        uses: docker/build-push-action@v4
        with:
          build-args: |
            gituser=${{ secrets.USERNAME }}
            gitpass=${{ secrets.PAT }}
          context: .
          file: ./src/Presentation/ClientServiceApi/Dockerfile
          tags: ${{ env.LATEST_TAG }}
          push: true


